// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// VendorsColumns holds the columns for the "vendors" table.
	VendorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString},
	}
	// VendorsTable holds the schema information for the "vendors" table.
	VendorsTable = &schema.Table{
		Name:       "vendors",
		Columns:    VendorsColumns,
		PrimaryKey: []*schema.Column{VendorsColumns[0]},
	}
	// VendorProductDetailsColumns holds the columns for the "vendor_product_details" table.
	VendorProductDetailsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "product_id", Type: field.TypeInt, Nullable: true},
		{Name: "vendor_id", Type: field.TypeInt, Nullable: true},
	}
	// VendorProductDetailsTable holds the schema information for the "vendor_product_details" table.
	VendorProductDetailsTable = &schema.Table{
		Name:       "vendor_product_details",
		Columns:    VendorProductDetailsColumns,
		PrimaryKey: []*schema.Column{VendorProductDetailsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "vendor_product_details_products_vendor_product_details",
				Columns:    []*schema.Column{VendorProductDetailsColumns[1]},
				RefColumns: []*schema.Column{ProductsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "vendor_product_details_vendors_vendor_product_details",
				Columns:    []*schema.Column{VendorProductDetailsColumns[2]},
				RefColumns: []*schema.Column{VendorsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ProductsTable,
		VendorsTable,
		VendorProductDetailsTable,
	}
)

func init() {
	VendorProductDetailsTable.ForeignKeys[0].RefTable = ProductsTable
	VendorProductDetailsTable.ForeignKeys[1].RefTable = VendorsTable
}
