name: inventory-dev
concurrency:
  group: inventory-dev
  cancel-in-progress: true

on:
  pull_request:
  push:
    paths:
      - ".github/**"
      - "pkg/**"
      - "service/inventory/**"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Download Go modules
        run: |
          make workspace=service/inventory download
          sudo make lint-install
      - name: Verify generated code for entgo
        uses: ent/contrib/ci@master
        with:
          working-directory: "./service/inventory"
      - run: docker -v
      - name: Start postgress docker 
        run: docker compose up postgres --detach
      - name: Run unit tests
        run: |
          make workspace=service/inventory test
      - name: Run lint
        run: |
          make workspace=service/inventory lint
