name: web-push-dev
concurrency:
  group: web-push-dev
  cancel-in-progress: true

on:
  pull_request:
  push:
    paths:
      - ".github/**"
      - "pkg/**"
      - "service/web_push/**"

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Download Go modules
        run: |
          make workspace=service/web_push download
          sudo make lint-install
      - name: Run unit tests
        run: |
          make workspace=service/web_push test
      - name: Run lint
        run: |
          make workspace=service/web_push lint
