// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Vendor is the predicate function for vendor builders.
type Vendor func(*sql.Selector)

// VendorProductDetail is the predicate function for vendorproductdetail builders.
type VendorProductDetail func(*sql.Selector)
