name: foodtruck-ui
concurrency:
  group: foodtruck-ui
  cancel-in-progress: true

on:
  - push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Print dir
        run: ls
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install node modules
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test:unit
        env:
          "STAGE": "test"
      - name: Run lint
        run: pnpm run lint
